<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 1

### 1. Create a null vector of size 7 but the third and last value as 2.

In [4]:
import numpy as np
def generate():
    vec = np.zeros(7)
    vec[6] = vec[2] = 2
    # Write your code here
    return vec# your variable 
print(generate())

[0. 0. 2. 0. 0. 0. 2.]


### 2. Create a vector of size 9 with values ranging from 0 to 2, both excluded.

In [11]:
import numpy as np
def generate():
    vec = np.random.randint(1,2,9)
    # Write your code here
    return vec# your variable
generate()

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

### 3. Convert the first character of each element in a series to uppercase? And return the new series.

In [23]:
import pandas as pd
series = pd.Series(['how', 'to', 'learn', 'data science?'])
def generate(series):             
    # your code
    return series.str.capitalize()# your variable for new series
generate(series) 

0              How
1               To
2            Learn
3    Data science?
dtype: object

### 4. Given a 3*3 matrix named matrix_fab, From each element of this matrix subtract the mean of that row, name this matrix as matrix_sub. Divide each element of this matrix by twice of the largest element to get matrix_norm. Print it out.

In [36]:
import numpy as np
arr = np.arange(0,9)                                
matrix_fab = arr.reshape(3,3)

def generate():
    matrix_sub = matrix_fab - matrix_fab.mean(1).reshape(3,1)
    matrix_norm = matrix_sub/(2*matrix_sub.max())
    print(matrix_sub)
    print(matrix_norm)
    # Write your code here
    # print matrix_norm
    return None
generate()

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
[[-0.5  0.   0.5]
 [-0.5  0.   0.5]
 [-0.5  0.   0.5]]


### 5. Create a random vector of size 12 , sort it in decreasing order, make 4*3 array using it.
Hint: use reshape and sort function.

In [44]:
import numpy as np
def generate():
    vec = np.sort(np.random.rand(12))
    vec = vec[::-1].reshape(4,3)
   # print(sort(vec))
    # Write your code here
    return vec# your variable
generate()

array([[0.99094213, 0.95778667, 0.9513655 ],
       [0.82660676, 0.79767412, 0.51641415],
       [0.34678378, 0.31457267, 0.28318906],
       [0.23574582, 0.21717093, 0.08443451]])

### 6. Below is Python dictionary data and Python list labels. Create a DataFrame df from this dictionary data which has index as labels. Select the rows where the age is missing, i.e. is NaN.

In [63]:
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
import pandas as pd

def generate():
    df = pd.DataFrame(data,index=labels)
    # Write your code here
    return df[:][df.age.notnull()] # your variable
generate()

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
i    dog  7.0       2       no
j    dog  3.0       1       no

### 7. From the give dataframe df, in the 'animal' column change the 'dog' entries to 'Labrador', change the age in row 'd' to 2.7 and calculate the mean age (name it mean_age) for each different animal in df. Print df and return mean_age.

In [84]:
import pandas as pd
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

def generate():
    df =  pd.DataFrame(data,index=labels)
    df.loc[df.animal == 'dog','animal'] = 'Labrador'
    df.loc['d','age'] = 2.7
    print(df)
    # write your code here
    # Also print df
    return df.age.mean() # your variable i.e mean_age
generate()




     animal  age  visits priority
a       cat  2.5       1      yes
b       cat  3.0       3      yes
c     snake  0.5       2       no
d  Labrador  2.7       3      yes
e  Labrador  5.0       2       no
f       cat  2.0       3       no
g     snake  4.5       1       no
h       cat  NaN       1      yes
i  Labrador  7.0       2       no
j  Labrador  3.0       1       no


3.3555555555555556

### 8.  From the given dataframe get the positions where values of two columns match?

In [111]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
def generate():
    print(df[(df['fruit1'] == df['fruit2'])].index)
    # your code here
    return None
generate()

Int64Index([0, 2, 7, 9], dtype='int64')


### 9. Find the positions of numbers that are multiples of 4 from a series? Print series and return position. Hint: use argwhere.

In [113]:
import pandas as pd
import numpy as np
series = pd.Series(np.random.randint(1, 10, 7))
def generate():
    # your code here
    print(series)
    return np.argwhere((series % 4 )==0) # your variable
generate()


0    8
1    4
2    1
3    8
4    5
5    3
6    4
dtype: int32


array([[0],
       [1],
       [3],
       [6]], dtype=int64)

### 10. Stack two given series vertically and horizontally ? Print out both.

In [123]:
import pandas as pd
import numpy as np
series1 = pd.Series(range(5))
series2 = pd.Series(list('abcde'))
def generate():
    print(np.hstack((series1,series2)))
    print(np.vstack((series1,series2)))
    # your code 
    # print out both vertically and horizontally stacked series.
    return None
generate()


[0 1 2 3 4 'a' 'b' 'c' 'd' 'e']
[[0 1 2 3 4]
 ['a' 'b' 'c' 'd' 'e']]
